export { ConfigManager } from './config/ConfigManager';
export { WatcherDatabase } from './database/Database';
export { FileMonitor } from './monitor/FileMonitor';
export { GitService } from './git/GitService';
export { CredentialManager } from './credentials/CredentialManager';
export { AIProviderFactory } from './ai/AIProviderFactory';
export { SemanticAnalyzer } from './ai/SemanticAnalyzer';
export { logger } from './utils/logger';
export * from './types';
export * from './types/ai';
